### ISSUE TITLE
MaxLengthReached: The value A BETTER LIFE-FLAGSTAFF exceed the max length: 20

### ISSUE THREAD

**Issue by D3WYAN** [kafi350/HL7toCSV#1]
How to get around the MaxLengthReached error?

**Comment by kafi350** [comment]
Hello, thank you for reaching out. Can you try the new file? 

I have pushed a fix.

**Comment by kafi350** [comment]
@D3WYAN Can you please check if this resolves the issue. For me it is working, even with a large hl7 file.
